### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by pianoman5001** [Jim-Duke/bumbyextras#33]
I am creating this issue for everyone to comment on with a list of new songs that you would like to be considered for addition into the next revision of the Bumby Extras hymnal. I think it will be better to simply list all the wanted songs here (instead of flooding the issues page) and then we can create the necessary issues for the next set of songs that we decide to work on or as we work on them.

**Comment by Jim-Duke** [comment]
This issue has served its purpose.
